### ISSUE TITLE
Logic: Date Formatter

### ISSUE THREAD

**Issue by Kelly-Chui** [DeveloperAcademy-POSTECH/MC2-Team10-NEW2KM#21]
DetailView와 그 하위 View들에서 시간을 표시하려면 Date Formatter가 필요합니다
제가 Hi-Fi 에서는 'Mar 26, 2022' 같은 식으로 표현했지만 표현을 좀 바꿔야 할 것 같아요.
ex)
1. 03/26/2022 -> DetailView
2. 3월 26일 -> MainView

두개의 Formatter가 필요하겠네요. 이 코드는 어디에 작성하는게 좋을까요 Utility?
<img width="155" alt="Screen Shot 2022-06-12 at 5 22 34 AM" src="https://user-images.githubusercontent.com/57012734/173203690-3fc16a94-58f7-4b57-8582-70a4b8d907fe.png">

노아, 메이는 꼭 확인해주세요

**Comment by Kelly-Chui** [comment]
하나의 함수는 하나의 기능만 하는게 프로그래밍 기본 원칙이므로 다 다른 메소드로 구현하겠습니다. 인자로 Boolean이나 Integer를 받아서 함수의 기능을 조절하는건 싫어요.

**Comment by PJunyeong** [comment]
Utility 폴더에 포매터 함수 만드는 게 좋겠네요. 어떤 형식이 적절할까요? (~월 ~일?)

**Comment by Kelly-Chui** [comment]
> Utility 폴더에 포매터 함수 만드는 게 좋겠네요. 어떤 형식이 적절할까요? (~월 ~일?)
> 예시로 작성하신 포맷인가요?

네 맞습니다. Formatter를 두개로 하는게 아니라 인자를 Date와 String으로 받아 String의 형태에 따라 Format을 출력하는 방식을 생각중입니다.(이미 구현했어요)
