### ISSUE TITLE
ERD

### ISSUE THREAD

**Issue by obtusa07** [DeveloperAcademy-POSTECH/MC2-Team10-NEW2KM#3]
데이터 자료구조 관련 브런치를 파서 #3 로 넣었습니다. 확인해주시고 수정 + 관련 이야기 이슈로 남겨주세요... assign에 에디, 메이도 추가해주세요! 못 찾겠어요...

**Comment by PJunyeong** [comment]
브런치에 올린 코드는 여기 이슈에서 직접 코드 단위로 댓글 달 수 있습니다!

**Comment by PJunyeong** [comment]
일단 대체적인 ERD 구조를 짜서 main에 PUSH했는데, 이 칸반이 있는지 까먹고 있었습니다 👀 살펴보시고 이상한 점/고쳐야 할 점/의문인 점 여기서 논의해봅시다! (브런치는 따로 파야겠군요 ㅠㅠ)

**Comment by sunshiningsoo** [comment]
JSON으로 바꾸어 이슈 Close
